### ISSUE TITLE
阻止自动填充帐号input

### ISSUE THREAD

**Issue by XXHolic** [XXHolic/html-css-point#4]
## 场景
在维护一个功能的时候，多个帐号切换登录的时候，微信内h5页面自动填充的帐号是错误的，需要阻止这种行为。试了网上几种方法，发现不行，最后找到了可用的方法，在此记录。测试页面点击[这里](https://xxholic.github.io/lab/lab-html/input-auto.html)。
## 方法
场景描述中尝试过但不可行的方法：
- 使用假的input让浏览器去填充，设置`display:none`或者`type:hidden`
- 在input使用属性`autocomplete="off"`
- 页面加载完后，用js将其置空

场景描述中可行的方法：
- 相关的input不使用id，获取值的时候用class来获取

PC端可行的方法：
- 在input使用属性`autocomplete="off"`，测试过浏览器中chrome(63.0.3239.132)、火狐（59.0.2）、360（9.1.0.410/55.0.2883.87）

## 样式重置
如果使用自动填充，但要去掉选中帐号后的黄色背景，使用样式：
```css
input:-webkit-autofill {
  -webkit-box-shadow: 0 0 0 1000px white inset !important;
}
```
## 参考
- http://www.cnblogs.com/huangtailang/p/5257631.html
- https://blog.csdn.net/theFrontCalf/article/details/78962123
- https://blog.csdn.net/QQ164881500/article/details/79271318
